name: Integration Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      strategy:
        matrix:
          node-version: [18, 20]

      steps:
        - name: Check out code
          uses: actions/checkout@v4

        - uses: pnpm/action-setup@v2
          with:
            version: 8

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'

        - name: Install dependencies
          run: pnpm install --frozen-lockfile

        - name: Build
          run: pnpm build

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-session-name: cloud-spec-tests
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Test
          run: pnpm test